ALTER TABLE person ADD id INTEGER;
ALTER TABLE person DROP id;

ALTER TABLE person RENAME TO R1;

ALTER TABLE R1 RENAME COLUMN email TO email_id;
ALTER TABLE person ALTER COLUMN  GENDER TYPE VARCHAR(10);